# Generated by Django 4.1.3 on 2022-12-31 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroDeProyecto', '0002_descripcionproyecto_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoIng',
            fields=[
                ('Proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroDeProyecto.proyecto')),
                ('Nombre', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=50)),
                ('CantidadDOC', models.IntegerField()),
                ('CantidaddeHs', models.IntegerField()),
                ('Costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CostosMateriales',
            fields=[
                ('Proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroDeProyecto.proyecto')),
                ('Codigo', models.CharField(max_length=50)),
                ('NombreMat', models.IntegerField()),
                ('CostoMat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CostosMontaje',
            fields=[
                ('Proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroDeProyecto.proyecto')),
                ('Contratista', models.CharField(max_length=50)),
                ('MontoContrato', models.IntegerField()),
            ],
        ),
    ]
