# Generated by Django 4.1.3 on 2022-12-31 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeProyecto', '0002_descripcionproyecto_avatar'),
        ('CostosProy', '0002_delete_costosmateriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50)),
                ('NombreMat', models.IntegerField()),
                ('CostoMat', models.IntegerField()),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroDeProyecto.proyecto')),
            ],
        ),
    ]
