# Generated by Django 4.1.3 on 2022-12-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CostosProy', '0003_materiales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='NombreMat',
            field=models.CharField(max_length=50),
        ),
    ]
