# Generated by Django 4.1.3 on 2023-01-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CostosProy', '0004_alter_materiales_nombremat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostosMontaje',
        ),
    ]
