# Generated by Django 4.1.3 on 2023-01-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeProyecto', '0003_descripcionproy_delete_descripcionproyecto'),
        ('CostosProy', '0005_delete_costosmontaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostosMontaje',
            fields=[
                ('Proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='RegistroDeProyecto.proyecto')),
                ('Contratista', models.CharField(max_length=50)),
                ('MontoContrato', models.IntegerField()),
            ],
        ),
    ]
