# Generated by Django 4.1.3 on 2023-01-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeProyecto', '0002_descripcionproyecto_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionProy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(default='Agregar un valor', max_length=1000)),
                ('Proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroDeProyecto.proyecto')),
            ],
        ),
        migrations.DeleteModel(
            name='DescripcionProyecto',
        ),
    ]
