# Generated by Django 4.1.3 on 2023-01-01 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroDeProyecto', '0003_descripcionproy_delete_descripcionproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombredereporte', models.CharField(max_length=50)),
                ('reporte', models.CharField(max_length=1500)),
                ('imagenReporte', models.ImageField(upload_to='IMGReporte')),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroDeProyecto.proyecto')),
            ],
        ),
    ]
